### ISSUE TITLE
Problem compiling imported .less files, e.g. Twitter Bootstrap

### ISSUE THREAD

**Issue by vgrichina** [davidmarquis/grails-lesscss#4]
LESS CSS: compiling .less files ...

Compiling LESS files from dir /Users/vg/.grails/1.3.6/projects/componentix_com/stage
Compiling LESS file [/Users/vg/.grails/1.3.6/projects/componentix_com/stage/css/lib/bootstrap.less] into [/Users/vg/.grails/1.3.6/projects/componentix_com/stage/css/lib/bootstrap.css]
Compiling LESS file [/Users/vg/.grails/1.3.6/projects/componentix_com/stage/css/lib/forms.less] into [/Users/vg/.grails/1.3.6/projects/componentix_com/stage/css/lib/forms.css]
   [delete] Deleting directory /Users/vg/.grails/1.3.6/projects/componentix_com/stage
Error executing script War: com.asual.lesscss.LessException: com.asual.lesscss.LessException: Error: variable @baseline is undefined (line 10, column 17) near
form {
  margin-bottom: @baseline;
}
com.asual.lesscss.LessException: com.asual.lesscss.LessException: Error: variable @baseline is undefined (line 10, column 17) near
form {
  margin-bottom: @baseline;
}
    at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:391)
    at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
    at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
    at gant.Gant.withBuildListeners(Gant.groovy:427)
    at gant.Gant.this$2$withBuildListeners(Gant.groovy)
    at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
    at gant.Gant.dispatch(Gant.groovy:415)
    at gant.Gant.this$2$dispatch(Gant.groovy)
    at gant.Gant.invokeMethod(Gant.groovy)
    at gant.Gant.executeTargets(Gant.groovy:590)
    at gant.Gant.executeTargets(Gant.groovy:589)
Caused by: com.asual.lesscss.LessException: com.asual.lesscss.LessException: Error: variable @baseline is undefined (line 10, column 17) near
form {
  margin-bottom: @baseline;
}
    at com.asual.lesscss.LessEngine.parseLessException(LessEngine.java:183)
    at com.asual.lesscss.LessEngine.compile(LessEngine.java:115)
    at com.github.grails.lesscss.LessEngineHelper$_compileLessCss_closure1.doCall(LessEngineHelper.groovy:26)
    at com.github.grails.lesscss.LessEngineHelper.compileLessCss(LessEngineHelper.groovy:14)
    at com.github.grails.lesscss.LessEngineHelper$compileLessCss.call(Unknown Source)
    at _Events.compileLessCss(_Events.groovy:36)
    at _Events$_run_closure2.doCall(_Events.groovy:16)
    at _GrailsEvents_groovy$_run_closure5.doCall(_GrailsEvents_groovy:58)
    at _GrailsEvents_groovy$_run_closure5.call(_GrailsEvents_groovy)
    at War$_run_closure5.doCall(War:334)
    at War$_run_closure1.doCall(War.groovy:38)
    at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
    ... 10 more
Caused by: com.asual.lesscss.LessException: Error: variable @baseline is undefined (line 10, column 17) near
form {
  margin-bottom: @baseline;
}
    at com.asual.lesscss.LessEngine.parseLessException(LessEngine.java:179)
    at com.asual.lesscss.LessEngine.compile(LessEngine.java:101)
    at com.asual.lesscss.LessEngine.compile(LessEngine.java:107)
    ... 20 more
--- Nested Exception ---
com.asual.lesscss.LessException: com.asual.lesscss.LessException: Error: variable @baseline is undefined (line 10, column 17) near
form {
  margin-bottom: @baseline;
}
    at com.asual.lesscss.LessEngine.parseLessException(LessEngine.java:183)
    at com.asual.lesscss.LessEngine.compile(LessEngine.java:115)
    at com.github.grails.lesscss.LessEngineHelper$_compileLessCss_closure1.doCall(LessEngineHelper.groovy:26)
    at com.github.grails.lesscss.LessEngineHelper.compileLessCss(LessEngineHelper.groovy:14)
    at com.github.grails.lesscss.LessEngineHelper$compileLessCss.call(Unknown Source)
    at _Events.compileLessCss(_Events.groovy:36)
    at _Events$_run_closure2.doCall(_Events.groovy:16)
    at _GrailsEvents_groovy$_run_closure5.doCall(_GrailsEvents_groovy:58)
    at _GrailsEvents_groovy$_run_closure5.call(_GrailsEvents_groovy)
    at War$_run_closure5.doCall(War:334)
    at War$_run_closure1.doCall(War.groovy:38)
    at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
    at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
    at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
    at gant.Gant.withBuildListeners(Gant.groovy:427)
    at gant.Gant.this$2$withBuildListeners(Gant.groovy)
    at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
    at gant.Gant.dispatch(Gant.groovy:415)
    at gant.Gant.this$2$dispatch(Gant.groovy)
    at gant.Gant.invokeMethod(Gant.groovy)
    at gant.Gant.executeTargets(Gant.groovy:590)
    at gant.Gant.executeTargets(Gant.groovy:589)
Caused by: com.asual.lesscss.LessException: Error: variable @baseline is undefined (line 10, column 17) near
form {
  margin-bottom: @baseline;
}
    at com.asual.lesscss.LessEngine.parseLessException(LessEngine.java:179)
    at com.asual.lesscss.LessEngine.compile(LessEngine.java:101)
    at com.asual.lesscss.LessEngine.compile(LessEngine.java:107)
    ... 20 more
Error executing script War: com.asual.lesscss.LessException: com.asual.lesscss.LessException: Error: variable @baseline is undefined (line 10, column 17) near
form {
  margin-bottom: @baseline;
}

**Comment by vgrichina** [comment]
Fixed in pull request #5

**Comment by davidmarquis** [comment]
ok I just released your updates as version 1.0.0 of the plugin. Thanks Vladimir!

**Comment by tolyo** [comment]
Still am getting this error. Reinstalled the plugin but getting same error:

Error executing script War: com.asual.lesscss.LessException: com.asual.lesscss.LessException: Error: variable @baseline is undefined (line 10, column 17) near
form {
  margin-bottom: @baseline;
}
com.asual.lesscss.LessException: com.asual.lesscss.LessException: Error: variable @baseline is undefined (line 10, column 17) near
form {
  margin-bottom: @baseline;
}
    at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:391)
    at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
    at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
    at gant.Gant.withBuildListeners(Gant.groovy:427)
    at gant.Gant.this$2$withBuildListeners(Gant.groovy)
    at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
    at gant.Gant.dispatch(Gant.groovy:415)
    at gant.Gant.this$2$dispatch(Gant.groovy)
    at gant.Gant.invokeMethod(Gant.groovy)
    at gant.Gant.executeTargets(Gant.groovy:590)
    at gant.Gant.executeTargets(Gant.groovy:589)
Caused by: com.asual.lesscss.LessException: com.asual.lesscss.LessException: Error: variable @baseline is undefined (line 10, column 17) near
form {
  margin-bottom: @baseline;
}
    at com.asual.lesscss.LessEngine.parseLessException(LessEngine.java:184)
    at com.asual.lesscss.LessEngine.compile(LessEngine.java:116)
    at com.asual.lesscss.LessEngine$compile.call(Unknown Source)
    at com.github.grails.lesscss.LessEngineHelper$_compileLessCss_closure1.doCall(LessEngineHelper.groovy:29)
    at com.github.grails.lesscss.LessEngineHelper.compileLessCss(LessEngineHelper.groovy:16)
    at com.github.grails.lesscss.LessEngineHelper$compileLessCss.call(Unknown Source)
    at _Events.compileLessCss(_Events.groovy:36)
    at _Events$_run_closure2.doCall(_Events.groovy:16)
    at _GrailsEvents_groovy$_run_closure5.doCall(_GrailsEvents_groovy:58)
    at _GrailsEvents_groovy$_run_closure5.call(_GrailsEvents_groovy)
    at _GrailsWar_groovy$_run_closure4.doCall(_GrailsWar_groovy:329)
    at War$_run_closure1.doCall(War:38)
    at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
    ... 10 more
Caused by: com.asual.lesscss.LessException: Error: variable @baseline is undefined (line 10, column 17) near
form {
  margin-bottom: @baseline;
}
    at com.asual.lesscss.LessEngine.parseLessException(LessEngine.java:180)
    at com.asual.lesscss.LessEngine.compile(LessEngine.java:102)
    at com.asual.lesscss.LessEngine.compile(LessEngine.java:108)
    ... 21 more
--- Nested Exception ---
com.asual.lesscss.LessException: com.asual.lesscss.LessException: Error: variable @baseline is undefined (line 10, column 17) near
form {
  margin-bottom: @baseline;
}
    at com.asual.lesscss.LessEngine.parseLessException(LessEngine.java:184)
    at com.asual.lesscss.LessEngine.compile(LessEngine.java:116)
    at com.asual.lesscss.LessEngine$compile.call(Unknown Source)
    at com.github.grails.lesscss.LessEngineHelper$_compileLessCss_closure1.doCall(LessEngineHelper.groovy:29)
    at com.github.grails.lesscss.LessEngineHelper.compileLessCss(LessEngineHelper.groovy:16)
    at com.github.grails.lesscss.LessEngineHelper$compileLessCss.call(Unknown Source)
    at _Events.compileLessCss(_Events.groovy:36)
    at _Events$_run_closure2.doCall(_Events.groovy:16)
    at _GrailsEvents_groovy$_run_closure5.doCall(_GrailsEvents_groovy:58)
    at _GrailsEvents_groovy$_run_closure5.call(_GrailsEvents_groovy)
    at _GrailsWar_groovy$_run_closure4.doCall(_GrailsWar_groovy:329)
    at War$_run_closure1.doCall(War:38)
    at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
    at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
    at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
    at gant.Gant.withBuildListeners(Gant.groovy:427)
    at gant.Gant.this$2$withBuildListeners(Gant.groovy)
    at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
    at gant.Gant.dispatch(Gant.groovy:415)
    at gant.Gant.this$2$dispatch(Gant.groovy)
    at gant.Gant.invokeMethod(Gant.groovy)
    at gant.Gant.executeTargets(Gant.groovy:590)
    at gant.Gant.executeTargets(Gant.groovy:589)
Caused by: com.asual.lesscss.LessException: Error: variable @baseline is undefined (line 10, column 17) near
form {
  margin-bottom: @baseline;
}
    at com.asual.lesscss.LessEngine.parseLessException(LessEngine.java:180)
    at com.asual.lesscss.LessEngine.compile(LessEngine.java:102)
    at com.asual.lesscss.LessEngine.compile(LessEngine.java:108)
    ... 21 more
Error executing script War: com.asual.lesscss.LessException: com.asual.lesscss.LessException: Error: variable @baseline is undefined (line 10, column 17) near
form {
  margin-bottom: @baseline;
}

**Comment by tolyo** [comment]
The code is not mine, but Twitter's. They define their variables in 
variables.less file and the compilation ordering is before the form.less 
where this problem starts appearing.

Important factor that I forgot to mention: it works in dev mode. In 
fact, the dev mode is where the problem would have been addressed via 
the less debugger if it were a less issue. 'war' script command is the 
only place where it appears.

**Comment by tolyo** [comment]
Renaming the files allows bypassing the issue: 'war' script builds the less files in numerical/alphabetical order.
